[workspace]
members = [
    "bxa-std",
    "bxa-abi",
    "bxa-api",
    "bxa-abi-derive",
    "examples/bxa",
    "examples/token",
    "bxa-gen-address",
]

[profile.release]
panic = "abort"
lto = true
debug = true
opt-level = "s"
