[package]
name = "bxa-gen-address"
version = "0.1.0"
authors = ["fospring <fospring@outlook.com>"]
edition = "2018"

[dependencies]
sha2 = "0.8.0"
ripemd160 = "0.8.0"
hex = "0.3.1"
serde_json = "1.0.39"
serde = {version = "1.0.90", features = ["derive"] }
clap = "~2.32"